### PR TITLE
Jlink check

### PR DESCRIPTION
**Pull request by utzig**
This avoids downloading the latest J-Link release, using instead a specific version for which a checksum file is present, and it was tested and is known to work without issues (hopefully).

### CODE REVIEW

**Comment by utzig** [comment]
This updates #7, "tagging" a specific release of J-Link.

**Comment by spoonofpower** [comment]
Instead of the JLink_Linux_V634h_x86_64.deb.md5 file, could we have JLink_Linux_V634h_x86_64.deb.sha256? The content would be:

```c657eef0dadef7103414f4141ecaf363502ab9f88812b92e28149b94bda0d855  JLink_Linux_V634h_x86_64.deb```

The check would be done with `shasum --check` instead of `md5sum --check`.  The main reason I bring this up is because `md5sum` doesn't exist on the mac. On the mac the command is `md5`. It would be nice if this worked on mac and linux. The `shasum` command is the same on both.

**Comment by utzig** [comment]
@spoonofpower done!

**Comment by spoonofpower** [comment]
Cool, thanks!

**Pull request merged**
