### PR TITLE
Update to Ubuntu bionic (18.04)

### PR DESCRIPTION
**Pull request by utzig**
This updates the image to build on Bionic, which brings in latest releases of tooling, eg:
    
- openocd 0.10.0
- gcc 7.3.0
- arm-none-eabi-gcc 7.3.1
- gdb 8.1.0
- arm-none-eabi-gdb 8.1.0
- jlink (always latest, currently 6.34)

Also added `make jlink-download` target to avoid requiring manual download.

### CODE REVIEW

**Comment by utzig** [comment]
This should close #3 and #4

**Comment by utzig** [comment]
I tested this with nrf52840pdk and nucleo-f767zi, able to create/build/load/debug both boards. Have not tested `newtmgr`.

If someone else has input or wants to test it as well, it is welcomed! @placrosse @rdagher

**Comment by rdagher** [comment]
@utzig Gr8, I will test it today and let you know asap

**Comment by rdagher** [comment]
Took the liberty of slightly modifying the makefile for automatic deb file download and md5 checksum verification. Since I couldn't update @utzig branch on his fork, [attached](https://gist.githubusercontent.com/rdagher/8eabdd6c16fc7ab26958a78e24925818/raw/2c0708599dd47d9b9493be7094a9e70feaad1f32/0001-Added-netcat-and-jlink-checksum.patch) is the corresponding patch.

I just successfully tested with rebear nano and decawave [dwm1000](https://github.com/Decawave/mynewt-dw1000-apps). Flashing via openocd and Jlink works, icluding segger RTT over telnet (port 19021).

That's cool, I can now work with a clean dev. environment. BTW, since running from docker, bash completion don't work, so if you guys have a trick, please let me know !

**Comment by utzig** [comment]
@rdagher Thanks for testing, I think those changes are OK, please submit them after this PR is merged!

**Comment by spoonofpower** [comment]
Thanks

**Pull request merged**
