### PR TITLE
Update newt/newtmgr to 1.4.1

### PR DESCRIPTION
**Pull request by utzig**
Updated go image because newt 1.4.x requires go 1.10.x.

Signed-off-by: Fabio Utzig <utzig@apache.org>

### CODE REVIEW

**Comment by utzig** [comment]
This should fix #3

**Comment by rdagher** [comment]
@utzig Is there any reason why openocd is still at 0.9? I have rebuild it from source in a a running container, and it seems to work:

```bash
$ apt-get update
$ apt-get purge openocd
$ apt-get install build-essential libtool pkg-config automake libusb-dev libusb-1.0-0-dev libhidapi-dev
$ git clone https://github.com/ntfreak/openocd && cd openocd
$ git checkout v0.10.0
$ ./bootstrap
$ ./configure --enable-stlink --enable-jlink --enable-ftdi --enable-cmsis-dap
$ make -j
$ make install 
```

It would be nice to update the Dokerfile so we can get the openocd version recommended by the doc..

Thanks,

**Comment by utzig** [comment]
@rdagher No, not any particular reason. It's mostly that every time something is upgraded, it needs to be tested, etc. If it is working for you, please submit a PR!

**Comment by utzig** [comment]
Btw, I think it would be better to stay on release versions, even though openocd does not release often, just to avoid any new bugs.

**Comment by rdagher** [comment]
> Btw, I think it would be better to stay on release versions, even though openocd does not release often, just to avoid any new bugs.

Yes definitely, that's why I checked out to the release tag after the clone. The ubuntu xenial repos are not updated wit the 0.10 version of opencd, but the bionic repos are up to date. 
I will test with some boards to make sure it works, and I will file a PR.

Finally, one can think the same of the Segger link deb file that is now at version V6.34h...

**Comment by utzig** [comment]
Yes, I built with `V6.34h` last week as well!

**Comment by spoonofpower** [comment]
Thanks @utzig

**Pull request merged**
